version: "3"

services:
  phoenix:
    build: .
    volumes:
      - ./api:/app
    ports:
      - "4000:4000"
  neo4j:
    image: neo4j:latest
    network_mode: "bridge"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - neo4jdata:/data
volumes:
  neo4jdata:
